name: 'Merge prevalence updates'

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize]
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'auto-prevalence-update')
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.MICROCOVID_BOT_PRIVATE_KEY }}
          app-id: ${{ secrets.MICROCOVID_BOT_APP_ID }}

      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.4.0
        with:
          ignoreActions: automerge
          checkInterval: 10
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: 'Merge'
        uses: pascalgn/automerge-action@v0.14.2
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: squash
          MERGE_LABELS: auto-prevalence-update
          UPDATE_LABELS: auto-prevalence-update
          # need to add a check for "behind"
